print("================================================")
print("Задачи по итераторам")
print("================================================")
print("1. Пройти по списку с помощью итератора")
numbers = [34, 63, 53, 93, 1, 0, 31]
num = iter(numbers)
print(next(num))
print(next(num))
print(next(num))
print(next(num))
print(next(num))
print(next(num))
print(next(num))

print("================================================")
print("2. Итератор для строки")
str_1 = "Николай 01234"
it_str_1 = iter(str_1)
print(next(it_str_1))
print(next(it_str_1))
print(next(it_str_1))
print(next(it_str_1))
print(next(it_str_1))
print(next(it_str_1))
print(next(it_str_1))
print(next(it_str_1))
print(next(it_str_1))
print(next(it_str_1))
print(next(it_str_1))
print(next(it_str_1))
print(next(it_str_1))

print("================================================")
